### ISSUE TITLE
make robot model according to string

### ISSUE THREAD

**Issue by aginika** [jsk-ros-pkg/jsk_visualization#227]
from [Discussion at ik-control.l](https://github.com/jsk-ros-pkg/jsk_visualization/pull/224/files#r21065683)

@garaemon 's suggestion
```
I think it should be handled in euscollada-robot.
My Idea is ...
1) add class method to euscollada-robot class (super class of all the robot) to create robot model according to robot name. like

(send euscollada-robot :create-robot-instance "HRP2JSKNT") ;; -> hrp2jsknt will be returned

2) when loading each robot model file, automatically add candidate to the class method.
```

**Comment by garaemon** [comment]
* about robot-interface https://github.com/jsk-ros-pkg/jsk_pr2eus/pull/97
* about robot-model https://github.com/euslisp/jskeus/pull/166

My idea is just using Meta-Object-Programming technique to find good class from current class hierarchy euslisp has.

So what you need is 
1. load all the files which defines robot-models and robot-interfaces you want to use.
2. use `make-robot-model-from-name` and `make-robot-interface-from-name` like
```
(setq *robot* (make-robot-model-from-name "pr2"))
(setq *ri* (make-robot-interface-from-name "hrp2jsknt"))
```

**Comment by garaemon** [comment]
Any feedback?

**Comment by snozawa** [comment]
If we have the rule that each robot has ``xx-init`` function,  how about this?
```
(setq robot-name "pr2")
(funcall (eval (read-from-string (format nil "#'~A-init" robot-name))))
```
By using this, we need to add any functions to create robot-model or robot interface.

**Comment by garaemon** [comment]
> By using this, we need to add any functions to create robot-model or robot interface.

Hmm, it works...

```lisp
(defun init-robot-from-name (robot-name)
   (funcall (eval (read-from-string (format nil "#'~A-init" robot-name))))
```

**Comment by garaemon** [comment]
better one

```lisp
(defun init-robot-from-name (robot-name &rest args)
   (apply (symbol-function (intern (string-upcase (format nil "~A-init" robot-name)))) args))
```

**Comment by garaemon** [comment]
Problem of this `init-robot-from-name` is that it setq different variable according to robot name.
for example, about HRP2JSKNT, `*hrp2jsknt*` is bound and about PR2, `*pr2` is bound.

**Comment by snozawa** [comment]
How about this?
```
(defun init-robot-from-name (robot-name &rest args)
   (apply (symbol-function (intern (string-upcase (format nil "~A-init" robot-name)))) args)
   (setq *robot* (eval (intern (string-upcase (format nil "*~A*" robot-name)))))
  )
```
In the case of euscollada-robots, robot instance global variable, robot-name, and robot class name are all same:
https://github.com/jsk-ros-pkg/jsk_model_tools/blob/master/euscollada/src/collada2eus.cpp#L1123

**Comment by garaemon** [comment]
it looks good.

I think we should have two functions:
* `make-robot-model-from-name` 

  multiple robot models are useful for planning

* `init-robot-from-name`

  Usefule


And I don't know if `make-robot-interface-from-nane` is useful or not

**Comment by snozawa** [comment]
Hmm, it is difficult.

> * `make-robot-model-from-name`
> multiple robot models are useful for planning

In https://github.com/euslisp/jskeus/pull/166, robot model is generated from `(instance* klass :init args)`. 
However, currently `*pr2*` is generated as pr2-sensor-robot class instance:
```
(defun pr2 () (setq *pr2* (instance pr2-sensor-robot :init)))
```
So, it is difficult to search adequate robot class from name like this:
https://github.com/euslisp/jskeus/pull/166/files#diff-c546f3a6798054fa253ce131ef3b2857R377

How about to use `(pr2)` function its self?

In the case of euscollada robots, currently generation functions seem to keep consistency such as `(pr2)` and `(pr2-init)`. 

So, we do not need to add any functions by using the following codes:
```
;; for model generation
(apply (symbol-function (intern (string-upcase (format nil "~A" robot-name)))) args)

;; for model + interface generation
(apply (symbol-function (intern (string-upcase (format nil "~A-init" robot-name)))) args)
```

**Comment by snozawa** [comment]
> And I don't know if make-robot-interface-from-nane is useful or not

Currently, I do not think we need robot-interface without robot model class, so we do not need `make-robot-interface-from-name` function.

**Comment by garaemon** [comment]
But (pr2) change value of *pr2*...

2015年1月29日木曜日、Shunichi Nozawa<notifications@github.com>さんは書きました:

> And I don't know if make-robot-interface-from-nane is useful or not
>
> Currently, I do not think we need robot-interface without robot model
> class, so we do not need make-robot-interface-from-name function.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jsk-ros-pkg/jsk_visualization/issues/227#issuecomment-71881025>
> .
>


-- 
from iPhone

**Comment by garaemon** [comment]
I think, about mode + interface generate, using `robot-init` function is reasonable.

However, about creating model, I prefer to make an instance of robot without any side-effect.
So I'd like to add make-robot-model-from-name function proposed in [here](https://github.com/euslisp/jskeus/pull/166)

**Comment by snozawa** [comment]
I agree with your opinion that it is preferable to avoid from using global variables. 

> I think, about mode + interface generate, using robot-init function is reasonable.

robot-init generates global variables such as `*ri*` and `*pr2*`.  It is also a problem.
(I thought you considered using `*pr2*` is not a problem because you agreed with using `pr2-init`)

If you generate robot model or robot interface (or both of them) without global variables, 
adding searching functions is reasonable:
https://github.com/euslisp/jskeus/pull/166
https://github.com/jsk-ros-pkg/jsk_pr2eus/pull/97

**Comment by garaemon** [comment]
> robot-init generates global variables such as *ri* and *pr2*. It is also a problem.
> (I thought you considered using *pr2* is not a problem because you agreed with using pr2-init)

I found that the side-effect would not be a problem.

side-effect of `*pr2*` woule be a problem only if we have multiple-robot model, but according to our discussion, in that case we can say `we should use make-robot-model-from-name` which is side-effect-free function.

**Comment by garaemon** [comment]
merged

Further discussion should be based on real-experience.
