### ISSUE TITLE
オーバーレイのプロットが重い

### ISSUE THREAD

**Issue by yuki-asano** [jsk-ros-pkg/jsk_visualization#301]
２００個表示すると10fpsくらいになる

**Comment by garaemon** [comment]
https://github.com/jsk-ros-pkg/jsk_visualization/pull/303
これで解決されるかも

**Comment by garaemon** [comment]
https://github.com/jsk-ros-pkg/jsk_visualization/pull/304
これでどうだろう

**Comment by garaemon** [comment]
https://github.com/jsk-ros-pkg/jsk_visualization/pull/305
これでどうだろうか

**Comment by garaemon** [comment]
200個はかなり厳しいようですね。VRAMとのやり取りに時間がかかっています

**Comment by garaemon** [comment]
ちなみに、サイズを小さくする(例えば128x128を10x10にする)と速くなります

**Comment by yuki-asano** [comment]
やっぱり3fpsですね。
outputのグラフが消えてしまいました。
tensionもしきい値が低いのかすぐに赤くなってしまいます。

**Comment by garaemon** [comment]
outputってなんですか

**Comment by yuki-asano** [comment]
アクチュエータの出力です。
一つのアクチュエータにつき二つ出ていたグラフの片方になります。

**Comment by garaemon** [comment]
どっち側ですか?

**Comment by yuki-asano** [comment]
左右で言う所の右側です

**Comment by garaemon** [comment]
円グラフか折れ線グラフかで教えてください

**Comment by yuki-asano** [comment]
そういう意味でしたか。
円グラフです。

**Comment by garaemon** [comment]
確認します

**Comment by garaemon** [comment]
> tensionもしきい値が低いのかすぐに赤くなってしまいます。

何割くらいから赤くなってほしいですか?
今は線形に色を変化させてしまっているのでいまいちかもしれない、非線形にしようかと思います

**Comment by yuki-asano** [comment]
今の設定がどのくらいか分からないのですが、
確か昔レンジが広すぎるとよくない感じだった気がするので、
30kgf(300N)を上限として、
20kgf(200N)くらいから赤くなるとうれしいのかなと思います。

**Comment by garaemon** [comment]
piechart消える問題は解決されたかと思います、チェックしてくれると助かります

**Comment by yuki-asano** [comment]
piechart復活しました。
ありがとうございます。

**Comment by garaemon** [comment]
大元の高速化については、ロボットモデルのみで20fps以上がでるようになったら最適化しようと思います。

この最適化は結構難しいです。。。

**Comment by yuki-asano** [comment]
はい、ロボットモデルの削減もおいおいやっていきたいと思います。

**Comment by garaemon** [comment]
その前に緊張やこびあんの高速化ですね

**Comment by garaemon** [comment]
一応今すぐできる所までは高速化したのでclose
