### ISSUE TITLE
Is it able to popup Strings or Numbers with Pictograms?

### ISSUE THREAD

**Issue by aginika** [jsk-ros-pkg/jsk_visualization#389]
We want to show some numbers as scores with Pictograms

**Comment by garaemon** [comment]
Please use marker for 3D text

**Comment by aginika** [comment]
Thanks a lot

**Comment by garaemon** [comment]
https://github.com/jsk-ros-pkg/jsk_visualization/blob/master/jsk_rviz_plugins/src/pictogram_display.cpp#L99

You may be able to support number by modifiying this function
