### ISSUE TITLE
How can I use the latest rqt_service_buttons?

### ISSUE THREAD

**Issue by wkentaro** [jsk-ros-pkg/jsk_visualization#401]
by running `rosrun rqt_gui rqt_gui` there are no buttons.
I think it should load default layout yaml file..
![image](https://cloud.githubusercontent.com/assets/4310419/7727589/ad4eb09c-ff44-11e4-9761-c0f7eaad45eb.png)

In 553e50bf742ecdc73a7d05b449f8fb99947d5317 ,
`rosrun jsk_rqt_plugins rqt_service_buttons` works.
![image](https://cloud.githubusercontent.com/assets/4310419/7727632/fb085496-ff44-11e4-9b87-9b5ccec02575.png)

**Comment by wkentaro** [comment]
Is this bug? Or should I do something more?

**Comment by garaemon** [comment]
You can find gear button on the right top

2015年5月20日水曜日、Kentaro Wada<notifications@github.com>さんは書きました:

> by running rosrun rqt_gui rqt_gui there are no buttons.
> I think it should load default layout yaml file..
> [image: image]
> <https://cloud.githubusercontent.com/assets/4310419/7727589/ad4eb09c-ff44-11e4-9761-c0f7eaad45eb.png>
>
> In 553e50b
> <https://github.com/jsk-ros-pkg/jsk_visualization/commit/553e50bf742ecdc73a7d05b449f8fb99947d5317>
> ,
> rosrun jsk_rqt_plugins rqt_service_buttons works.
> [image: image]
> <https://cloud.githubusercontent.com/assets/4310419/7727632/fb085496-ff44-11e4-9b87-9b5ccec02575.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jsk-ros-pkg/jsk_visualization/issues/401>.
>


-- 
✉︎ from iPhone

**Comment by wkentaro** [comment]
Thanks. It was hard to find the way to use this.
because below does not work.
```
rosrun jsk_rqt_plugins rqt_service_buttons _layout_file:=/jsk_rqt_plugins/resource/service_button_layout.yaml
```

![image](https://cloud.githubusercontent.com/assets/4310419/7733542/c65aaad4-ff6a-11e4-9ab5-6bd19c6fc0bb.png)

**Comment by wkentaro** [comment]
I had to type full path after click the gear mark.
To make it easy to use this package for other users, I will add README for this.

**Comment by garaemon** [comment]
jsk_visualization is not well documented, please add README

**Comment by wkentaro** [comment]
I sent PR : https://github.com/jsk-ros-pkg/jsk_visualization/pull/404/files
