### ISSUE TITLE
Documentation like jsk_recognition

### ISSUE THREAD

**Issue by garaemon** [jsk-ros-pkg/jsk_visualization#485]
I'd like to add documentation to jsk_visualization like jsk_recognition.

@wkentaro Could you prepare readthedocs?

**Comment by garaemon** [comment]
https://readthedocs.org/projects/jsk-visualization/
I've just enabled readthedocs.

**Comment by wkentaro** [comment]
Sure.

**Comment by garaemon** [comment]
jsk_rviz_pluginsのドキュメントの先頭に画像をタイル形式で自動で出力できたりしないものかな?

**Comment by wkentaro** [comment]
![image](https://cloud.githubusercontent.com/assets/4310419/10273442/8dfe6e74-6b6b-11e5-9c1a-267775910364.png)
ここですか．

**Comment by garaemon** [comment]
そう、そしていちいちrstに画像リスト書くのは面倒なので、なんかうまいことできないものか

**Comment by wkentaro** [comment]
tile状にした画像を書き出すプログラムをpure pythonで書けばreadthedocs上で画像を生成するとかが可能だと思います．（gitのログに残さない綺麗な方法）

**Comment by garaemon** [comment]
イメージとしては、[こういうページ](http://matplotlib.org/gallery.html)にしたい

**Comment by wkentaro** [comment]
いいと思います．
