### ISSUE TITLE
How to use video_capture?

### ISSUE THREAD

**Issue by wkentaro** [jsk-ros-pkg/jsk_visualization#491]
![image](https://cloud.githubusercontent.com/assets/4310419/10246575/7d08db2e-694d-11e5-8ecb-876181a73dd2.png)

I have StatueError (NOT Writable)

**Comment by garaemon** [comment]
I found that it is difficult to know a file is writable without creating file.
Now the status error is based on `access` result but it returns true if **file exists** and file is writable.

**Comment by wkentaro** [comment]
so should the user do `touch output.avi` at `~/.ros`?

**Comment by garaemon** [comment]
> so should the user do touch output.avi at ~/.ros?

yes but I disabled this feature. https://github.com/jsk-ros-pkg/jsk_visualization/pull/492

**Comment by wkentaro** [comment]
> I found that it is difficult to know a file is writable without creating file.

Is that impossible to check the access right of the directory in which the movie file will be created?

**Comment by garaemon** [comment]
> Is that impossible to check the access right of the directory in which the movie file will be created?

possible, just a second.

**Comment by wkentaro** [comment]
Thanks.

**Comment by garaemon** [comment]
done https://github.com/jsk-ros-pkg/jsk_visualization/pull/494

**Comment by garaemon** [comment]
In fact, I don't recomment to use video capture because it cannot resolve fps correctly.
 I recommend to use glc.
