### ISSUE TITLE
tile images on top page of readthedocs

### ISSUE THREAD

**Issue by wkentaro** [jsk-ros-pkg/jsk_visualization#502]
suggested at: https://github.com/jsk-ros-pkg/jsk_visualization/issues/485#issuecomment-145431501
by: @garaemon 

like http://matplotlib.org/gallery.html

assigned to: @wkentaro

**Comment by wkentaro** [comment]
方法案

* tile_images.py(pure python without opencv)をdoc/以下に置く
* tile_images.pyはドキュメント生成時に実行される
* tile_images.pyはdoc/jsk_rviz_plugins/imagesを見てすべてをタイル状にした画像を出力する
* doc/jsk_rviz_plugins/index.rstにタイル状の画像を載せる

**Comment by wkentaro** [comment]
ただこうなると、それぞれの画像にリンク貼りたいとかになりますよね。。
ということは、index.rstを生成する実行ファイルという話になります。

**Comment by garaemon** [comment]
まじめにやると、mdやらrstのASTを作って画像のリストを作るみたいに成りますが、sed的なもので適当にできるんじゃないかなと思ってます。

**Comment by garaemon** [comment]
たとえば、texから画像ファイルを抜き出して、そのファイルを調べるスクリプト

```
#!/bin/bash

TEXFILE=2015-Humanoids-ueda-drc-system.tex

FILES=$(grep "\.png\|\.jpg\|\.jpeg\|\.eps\|\.PNG\|\.JPG\|\.JPEG\|\.EPS" $TEXFILE | sed -e "s/.*{\(.*\)}.*/\1/")
ls -lht $FILES -S
```

**Comment by wkentaro** [comment]
画像ファイルはすべてimagesフォルダにあるからそれを全部並べればいいということではないですか？

**Comment by garaemon** [comment]
そうかも。png -- mdの対応関係がほしいと思うので、適当に正規表現で抜き出したら対応付けは作れる気がしますね

**Comment by wkentaro** [comment]
確かに画像ファイルの名前が必ずしも
* mask_image_to_point_indices1.png
* mask_image_to_point_indices2.png
* mask_image_to_point_indices.md
みたいにはなっていなそうですね。

**Comment by garaemon** [comment]
逆にそういう命名速に合わせる、というのもありですね。

**Comment by wkentaro** [comment]
個人的には命名則派ですかね。シンプルなので。

**Comment by wkentaro** [comment]
rstでtableを使えばこんな感じで出来ました。
https://github.com/wkentaro/inbox/blob/master/rst-tile-images-with-link/index.rst

**Comment by wkentaro** [comment]
これならスクリプトで作るのも簡単そうです。

**Comment by wkentaro** [comment]
こんな感じでしょうか。
![image](https://cloud.githubusercontent.com/assets/4310419/10300353/2dfa54aa-6c30-11e5-94be-41df4ee2f5d5.png)

**Comment by garaemon** [comment]
良い感じだと思います
