### ISSUE TITLE
BoundingBoxのshow_coordsがおかしい

### ISSUE THREAD

**Issue by YuOhara** [jsk-ros-pkg/jsk_visualization#528]
https://github.com/jsk-ros-pkg/jsk_recognition/issues/1360
で報告されていることですが、ここにあるコードがおかしい可能性があります。
https://github.com/jsk-ros-pkg/jsk_visualization/pull/420
のような修正が必要でしょうか。

**Comment by garaemon** [comment]
たぶんそう
