### ISSUE TITLE
License question

### ISSUE THREAD

**Issue by amc-nu** [jsk-ros-pkg/jsk_visualization#594]
Thank you for sharing such a great project.

Could you tell me what kind of license does your jsk visualization tool for Rviz hold?

Thanks

**Comment by k-okada** [comment]
its bsd
https://github.com/jsk-ros-pkg/jsk_visualization/blob/master/jsk_visualization/package.xml#L14
,
you're free to use
--
◉ Kei Okada

**Comment by amc-nu** [comment]
Thanks for your prompt response!
