### ISSUE TITLE
jsk_rviz_plugins OverlayText - How to show multiple texts, and what fonts are available?

### ISSUE THREAD

**Issue by marklewis3000** [jsk-ros-pkg/jsk_visualization#629]
I have 2 questions about using jsk_rviz_plugins / OverlayText

The OverlayText demo shows the following text being displayed:
    "You can write several text to show the operator  ...   you can choose font"

1) How can you display more than one OverlayText at the same time?
    Hopefully without requiring one publisher for each text, maybe using and ID or Name??

2) What other fonts are available besides "DejaVu Sans Mono" ?

Thank you

**Comment by wkentaro** [comment]
> 1) How can you display more than one OverlayText at the same time?
Hopefully without requiring one publisher for each text, maybe using and ID or Name??

To display text more than one OverlayText, the plugin requires one publisher for each text.

**Comment by wkentaro** [comment]
Probably #630 works.

**Comment by wkentaro** [comment]
Fixed?

**Comment by marklewis3000** [comment]
Sorry, but to test this, where is the latest binary/debian or how do I find and install the latest build?

**Comment by wkentaro** [comment]
```
cd
mkdir -p catkin_ws/jsk_visualization_ws/src
cd catkin_ws/jsk_visualization_ws/src
git clone https://github.com/jsk-ros-pkg/jsk_visualization.git
cd ..
catkin init
rosdep install --from-path . -r -y
catkin build jsk_rviz_plugins
```

**Comment by marklewis3000** [comment]
Sorry. I've been using catkin_make instead of catkin. So I installed catkin and pip, and I have now tried to build with catkin using your instructions above, and I think it completed. How then do you install the newly generated plugin into my rviz?

**Comment by wkentaro** [comment]
```
source ~/catkin_ws/jsk_visualization_ws/devel/setup.bash
rospack find jsk_rviz_plugins  # this should be ~/catkin_ws/jsk_visualization_ws/src/jsk_visualization/jsk_rviz_plugins
roslaunch jsk_rviz_plugins overlay_sample.launch
```

**Comment by marklewis3000** [comment]
Yes, once I checkbox 'Overtake Color Properties' the 'font' property appears, and I can select from among about 100 listed fonts.

**Comment by wkentaro** [comment]
Sounds good. If your problem is resolved, please close this issue.

**Comment by marklewis3000** [comment]
Latest update shows the available fonts for OverlayText. Closing issue
