### ISSUE TITLE
 caption contents for Plotter2D and PieChart in jsk_rviz_plugins?

### ISSUE THREAD

**Issue by marklewis3000** [jsk-ros-pkg/jsk_visualization#634]
The caption for Plotter2D is simply '**Plotter2D**', and likewise, the caption for PieChart is simply '**PieChart**'.

I would like to customize the caption as needed, such as '**Newtons**' and  '**Meters/Sec**'.

How can this be done? I don't see a property for the contents of the captions.

Thank you

**Comment by k-okada** [comment]
Please look at #636, that will solve your problem, Also this will be released as deb very soon.

**Comment by k-okada** [comment]
may be we do not have to change anything, just to rename plugins display name as described in http://docs.ros.org/jade/api/rviz/html/user_guide/#naming-displays,

![screenshot from 2016-09-13 01 52 27](https://cloud.githubusercontent.com/assets/493276/18444864/f45dfde4-7955-11e6-8ace-8143a9615736.png)
![screenshot from 2016-09-13 01 52 42](https://cloud.githubusercontent.com/assets/493276/18444870/f85722cc-7955-11e6-8a16-7d577ca6df85.png)

Hope this helps

**Comment by marklewis3000** [comment]
Using the 'Rename' button near the bottom of the' Displays' panel does change the Caption. Thank you!
