### ISSUE TITLE
How to use the jsk_rviz_plugins for Kinetic?

### ISSUE THREAD

**Issue by longjie** [jsk-ros-pkg/jsk_visualization#648]
Hello,

What is the easiest way to use the jsk_rviz_plugins for Kinetic?
Is there any script files or .rosinstall to get all I need?

Thank you,

**Comment by wkentaro** [comment]
Currently, we don't support kinetic and no .rosinstall for that.
At first, we need to create `.travis.kinetic` like [`.travis.hydro`](https://github.com/jsk-ros-pkg/jsk_visualization/blob/master/.travis.rosinstall.hydro).

**Comment by longjie** [comment]
I see, it must not be difficult even for me.
I just wanted to know if I have a wiser way.
Thank you!

**Comment by wkentaro** [comment]
```
% for pkg in $(rospack depends jsk_rviz_plugins); do                                                                                          │···············
  rosdep resolve $pkg --rosdistro kinetic --os=ubuntu:xenial &>/dev/null || echo $pkg;                                                        │···············
done                                                                                                                                          │···············
jsk_recognition_msgs                                                                                                                          │···············
jsk_recognition_utils

% for pkg in $(rospack depends jsk_rqt_plugins); do
  rosdep resolve $pkg --rosdistro kinetic --os=ubuntu:xenial &>/dev/null || echo $pkg;
done

% for pkg in $(rospack depends jsk_interactive_marker); do
  rosdep resolve $pkg --rosdistro kinetic --os=ubuntu:xenial &>/dev/null || echo $pkg;
done
ml_classifiers
libccd
fcl
jsk_recognition_msgs
jsk_recognition_utils
resized_image_transport
robot_self_filter
jsk_pcl_ros_utils
rethink_ee_description
baxter_description
jsk_pcl_ros
jsk_rviz_plugins
euscollada
pr2_controllers_msgs
pr2eus
pr2eus_moveit

% for pkg in $(rospack depends jsk_interactive); do
  rosdep resolve $pkg --rosdistro kinetic --os=ubuntu:xenial &>/dev/null || echo $pkg;
done
ml_classifiers
libccd
fcl
jsk_recognition_msgs
jsk_recognition_utils
resized_image_transport
robot_self_filter
jsk_pcl_ros_utils
rethink_ee_description
baxter_description
jsk_pcl_ros
jsk_rviz_plugins
euscollada
pr2_controllers_msgs
pr2eus
pr2eus_moveit
jsk_interactive_marker

% for pkg in $(rospack depends jsk_interactive_test); do
  rosdep resolve $pkg --rosdistro kinetic --os=ubuntu:xenial &>/dev/null || echo $pkg;
done
ml_classifiers
libccd
fcl
jsk_recognition_msgs
jsk_recognition_utils
resized_image_transport
robot_self_filter
jsk_pcl_ros_utils
rethink_ee_description
baxter_description
jsk_pcl_ros
jsk_rviz_plugins
euscollada
pr2_controllers_msgs
pr2eus
pr2eus_moveit
jsk_interactive_marker
jsk_interactive
```

**Comment by longjie** [comment]
Hmm, it seems jsk_rviz_plugins have much more unmet dependencies in Kinetic, such as jsk_perception related packages. It may take some times.

Jade is OK, I could build jsk_rviz_plugins in Jade, after all jsk binary packages installed. 

Thanks anyway,

**Comment by k-okada** [comment]
you do not have to compile jsk_rviz_plugins, jade is already released as
deb package
https://github.com/ros/rosdistro/pull/12852
http://repositories.ros.org/status_page/ros_jade_default.html?q=jsk_rviz_plugins&s=1

--
◉ Kei Okada


2016-11-28 17:44 GMT+09:00 Ron Tajima <notifications@github.com>:

**Comment by wkentaro** [comment]
@longjie For kinetic, you only need to install jsk_recognition from source.
(for jsk_rviz_plugins or jsk_rqt_plugins)
https://github.com/jsk-ros-pkg/jsk_visualization/pull/649/files#diff-a9585a05e3e573d88fd2506df53f7bee

The test on https://github.com/jsk-ros-pkg/jsk_visualization/pull/649 passes, so please see it for more detail.

**Comment by longjie** [comment]
Yeah, I see. I'm closing this issue when we can build it (actually my colleague is doing). 
We may be happier sticking to Jade for a while. BTW thank you for your support!

**Comment by furushchev** [comment]
`jsk_rviz_plugins` works on kinetic for now. I think it is ok to close this issue.

**Comment by kargarisaac** [comment]
It has a lot of dependencies for kinetic. Every time I add the required package, it needs another one.
Is there any pipeline to do it?

**Comment by knorth55** [comment]
@kargarisaac what do you mean?
if you don't want to install a lot of dependencies  again and again, it is better to make docker image for your own use case.

**Comment by kargarisaac** [comment]
> @kargarisaac what do you mean?
> if you don't want to install a lot of dependencies again and again, it is better to make docker image for your own use case.

I mean when I clone one package, it needs another one, then another ... . I continued it but it didn't finish ...

**Comment by knorth55** [comment]
@kargarisaac  do not use packages from source.
use debian packages.
just type `sudo apt install ros-kinetic-jsk-rviz-plugins`
