### ISSUE TITLE
PolygonArray is always rendered as black color.

### ISSUE THREAD

**Issue by pxlong** [jsk-ros-pkg/jsk_visualization#685]
Hi, thanks for sharing this great rviz plugin.

I use `jsk_recognition_msgs::PolygonArray` in Ubuntu 16.04 + ROS Kinetic. 
The polygon array is always filled with black color in rviz when I disable "only border" and change "coloring" to Flat color, no matter what color I picked.

**Comment by k-okada** [comment]
Sorry that I can not reproduce this problem
Can you try with this sample code to publish `jsk_recognition_msgs::PolygonArray` ?
```
rosrun jsk_rviz_plugins polygon_array_sample.py
```
and could visualize in rviz, I have tested in both deb (2.1.1) and latest source (2.1.3+)
![screenshot from 2018-01-24 19-57-03](https://user-images.githubusercontent.com/493276/35328913-4b13ddd8-0141-11e8-963c-5a6c421e055a.png)

**Comment by pxlong** [comment]
Hi @k-okada, many thanks for the quick reply.

I recorded a video to show the problem. Please check: https://youtu.be/NufN7DZCzYU 
It will not always rendered with black, the color will change according to the viewpoint. At some viewpoints, the color seen by human's eye is black.

**Comment by k-okada** [comment]
OK, though I can not see your video as follows
![screenshot from 2018-01-24 23-00-19](https://user-images.githubusercontent.com/493276/35341037-0a5fb6f0-0168-11e8-9a98-31d29c9644dc.png)

I think I can understand your situation, how about https://github.com/jsk-ros-pkg/jsk_visualization/pull/686 ? Will this solve your problem?
I'm not sure about your usecases, but in some situation, for example display float plane in 3D point cloud scene,current setting  will help, so I added 'enable lighting' property 

![screenshot from 2018-01-25 00-37-12](https://user-images.githubusercontent.com/493276/35341140-4f5c6e9c-0168-11e8-839d-c92d6ff2cc4f.png)
![screenshot from 2018-01-25 00-37-17](https://user-images.githubusercontent.com/493276/35341143-5194b0b6-0168-11e8-94a9-eb11d2da1696.png)

**Comment by pxlong** [comment]
@k-okada, sorry for the unplayable video, I am sure you can see it now: https://youtu.be/NufN7DZCzYU.
Thanks

**Comment by pxlong** [comment]
Hi @k-okada, thanks so much, #686 perfectly solve my issue.
