### ISSUE TITLE
Convex Bounding Box

### ISSUE THREAD

**Issue by ClementLeBihan** [jsk-ros-pkg/jsk_visualization#690]
Hi,

I would like to know if there exist a Convex Bounding Box. I found this image on the web, and would like to use this box in RVIZ with my convex clusters. 

It's seems that it doesn't exist in the jsk_rviz_plugin, but you might be able to help me.

Thank you,
Best,
ClémentLB

![1 jx_vhtmqbtwmrubf6xoxwg](https://user-images.githubusercontent.com/12940019/38687300-a2283bf6-3e76-11e8-948a-3a5d19e6a52a.png)

**Comment by ClementLeBihan** [comment]
Hi @iory !

I didn't see you answered me ! Yes I saw it was possible by using Marker but I prefer jsk because you can set LineWith, Color etc from rviz panel !

In fact I changed a little bit the way I express the polygon and now it's a nice convex-hull polygon exactly like the image !

**Comment by wkentaro** [comment]
@ClementLeBihan Have you changed the rviz plugin of Marker? I think it is better to add feature to  the marker plugin to change color, line width, etc.
