### ISSUE TITLE
Release request of 2.1.3 on Kinetic

### ISSUE THREAD

**Issue by knorth55** [jsk-ros-pkg/jsk_visualization#691]
Kinetic is still `2.1.1`. I want to use `2.1.3`.

**Comment by k-okada** [comment]
https://github.com/ros/rosdistro/pull/17891

--
◉ Kei Okada


2018-05-18 13:41 GMT+09:00 Shingo Kitagawa <notifications@github.com>:

**Comment by knorth55** [comment]
@k-okada thank you !
