### ISSUE TITLE
Polygons are not solid

### ISSUE THREAD

**Issue by chinitaberrio** [jsk-ros-pkg/jsk_visualization#697]
Hi all!

I'm publishing 121 polygons in a polygon array, in rviz i can only see the border of the polygon (here the only border box is ticked)

![image](https://user-images.githubusercontent.com/30284346/41701590-5efc9a76-7570-11e8-9965-535c5b711588.png)

When the "only border" box is not ticked i can't see anything regarding the polygons.

![image](https://user-images.githubusercontent.com/30284346/41701667-a07db638-7570-11e8-812b-6abdcfe40e61.png)

Any idea of what could be the issue?

S.

**Comment by furushchev** [comment]
@chinitaberrio Could you paste a content of the published message for further debugging? (If this problem happens even the number of polygons is only one, then please paste the message on that case)

**Comment by chinitaberrio** [comment]
Here the published message.
[output.txt](https://github.com/jsk-ros-pkg/jsk_visualization/files/2122525/output.txt)

Thanks.

**Comment by furushchev** [comment]
@chinitaberrio Could you also set `frame_id` of a header for each polygons members and check if it works?

**Comment by chinitaberrio** [comment]
It worked! thanks!

**Comment by furushchev** [comment]
@chinitaberrio 
Great!
I'll create a pull request to show error on this situation later to let users notice easier.
