### ISSUE TITLE
Need a new Debian release

### ISSUE THREAD

**Issue by awatson3** [jsk-ros-pkg/jsk_visualization#716]
The current release is 1 year old (Oct '17).  Please issue a new release from Master for those of us using aptitude.  There are important updates (like #686) that our team would like to see in the Debian package.  Thanks!

**Comment by YutoUchimi** [comment]
2.1.5 is already released, so close this issue.
indigo: https://github.com/ros/rosdistro/pull/20332
kinetic: https://github.com/ros/rosdistro/pull/20333
melodic: https://github.com/ros/rosdistro/pull/20334
