### ISSUE TITLE
Change size of pictogram

### ISSUE THREAD

**Issue by norala22** [jsk-ros-pkg/jsk_visualization#722]
I am currently trying to use pictograms from FontAwesome in my Rviz visualization.  
Is it possible to change the size of the icon/pictogram? I tried all possible fields (including .size) to change the size of the pictogram, but nothing worked. Thanks

**Comment by iory** [comment]
Thanks for your issue report!
Could you let me know your environment?

In my environment 
```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.5 LTS
Release:        16.04
Codename:       xenial
$ sudo dpkg --list | grep jsk-rviz-plugins
ii  ros-kinetic-jsk-rviz-plugins                                2.1.4-0xenial-20181117-040432-0800                    amd64        The jsk_rviz_plugins package
```
I can successfully changed size of pictograms.

### size == 1

![rviz-_009](https://user-images.githubusercontent.com/4690682/51953181-bbfe5f80-247e-11e9-9267-8a1cb8543c38.png)

### size == 2

![rviz-_010](https://user-images.githubusercontent.com/4690682/51953184-c0c31380-247e-11e9-8ede-1871e49769c2.png)

**Comment by mqcmd196** [comment]
Close there has been no movement for a while.
