### ISSUE TITLE
[jsk_rviz_plugins] video_capture start via topic

### ISSUE THREAD

**Issue by darkdragon-001** [jsk-ros-pkg/jsk_visualization#743]
I have a big number of rosbags from which I want to record video.
So I setup rviz and then want to record a video for each bag file.
It would help a lot, if I could set filename and trigger start/stop with a topic. Is this possible in addition to the manual text field and check box?

**Comment by peci1** [comment]
No, it's not possible. There is, however, a workaround. You can use RvizScenePublisher and record the published image topic containing the whole rviz view. To convert that to a MP4 video, run image_view video_recorder connected to the rviz image topic.
