### ISSUE TITLE
Plotter2D cannot display more than 5 digits/characters

### ISSUE THREAD

**Issue by xmfcx** [jsk-ros-pkg/jsk_visualization#760]
Plotter2D cannot display more than 5 digits/characters including the dot.

No matter which control I tweak, biggest number it can show is 999.9 and doesn't let me change size of the number in the center.

![Screenshot_2020-01-16_13-00-27](https://user-images.githubusercontent.com/10751153/72515534-227fb780-3861-11ea-8cc0-5d6978d7aa8e.png)

**Comment by mqcmd196** [comment]
Please try https://github.com/jsk-ros-pkg/jsk_visualization/pull/878

**Comment by xmfcx** [comment]
Thanks @mqcmd196 , this issue is resolved by:
- https://github.com/jsk-ros-pkg/jsk_visualization/pull/878
