### ISSUE TITLE
We should warn "PoseArray rviz plugin is deprecated in Kinetic, Melodic and Noetic"

### ISSUE THREAD

**Issue by knorth55** [jsk-ros-pkg/jsk_visualization#785]
`PoseArray` rviz plugin is added in `jsk_visualization` for `indigo` and `hyrdo` devel because of upstream late response.
https://github.com/jsk-ros-pkg/jsk_visualization/pull/349

However, the situation got changed, and we can use `pose array` default plugin in Kinetic, Melodic and Noetic...
Maybe we should warn that JSK version is deprecated, and switch to use `rviz` default plugin.

PR to rviz for hydro (closed)
https://github.com/ros-visualization/rviz/pull/858

PR to rviz for kinetic
https://github.com/ros-visualization/rviz/pull/1022

cc. @pazeshun

**Comment by pazeshun** [comment]
Currently, rviz dies when we load `PoseArray` in `jsk_rviz_plugins` subscribing messages whose elements are all zero.
You can check it by:
```
rosbag play poses_causing_rviz_death.bag --clock --loop
rviz -d poses_causing_rviz_death.rviz
```
`poses_causing_rviz_death.bag`: https://drive.google.com/file/d/1td4nojPODCbxojYSeR7w19T3aRxSg389/view?usp=sharing
`poses_causing_rviz_death.rviz`: https://gist.github.com/pazeshun/beeb9415db2611561644f5f1f6400d82
