### ISSUE TITLE
jsk_visualization readthedoc is not updated since 2018.12.18

### ISSUE THREAD

**Issue by knorth55** [jsk-ros-pkg/jsk_visualization#787]
jsk_visualization readthedoc is not updated sincd 2018.12.18
https://jsk-visualization.readthedocs.io/en/latest/
https://readthedocs.org/projects/jsk-visualization/builds/

related: https://github.com/jsk-ros-pkg/jsk_docs/issues/25

**Comment by k-okada** [comment]
@garaemon is the owner of https://readthedocs.org/projects/jsk-visualization/ and we could not configure that. @garaemon, Could you add me as maintainer? or remove the project?

**Comment by knorth55** [comment]
@garaemon hi, I also want to give us permission for jsk-visualization readthedocs project.

**Comment by garaemon** [comment]
Sorry for my late response.

I've just removed the jsk-visualization project from readthedocs.
Could you create a new version of jsk-visualization on readthedocs?

**Comment by k-okada** [comment]
@garaemon thank you!! created enw one https://jsk-visualization.readthedocs.io/en/latest/index.html
