### ISSUE TITLE
Links in Readme are outdated

### ISSUE THREAD

**Issue by orzechow** [jsk-ros-pkg/jsk_visualization#815]
First of all: Thanks for the nice visualization tools! :)

Small issue: The gallery links in the readme are outdated.

E.g. instead of  
https://jsk-docs.readthedocs.io/en/latest/jsk_visualization/doc/jsk_rviz_plugins
the docs are here:  
https://jsk-visualization.readthedocs.io/en/latest/jsk_rviz_plugins/index.html

**Comment by knorth55** [comment]
@orzechow thank you. I update the readme #816
