### ISSUE TITLE
change colur of PieCart with code

### ISSUE THREAD

**Issue by OmerKonan** [jsk-ros-pkg/jsk_visualization#839]
Hello, I want to use piechart as a warning info and I want to change color based on input value. Is there a way to change the color using my code?

**Comment by shmpwk** [comment]
The easiest way is to change the piechart color on rviz manually and save the config. 
e.g. According to the  [piechart doc](https://jsk-visualization.readthedocs.io/en/latest/jsk_rviz_plugins/plugins/pie_chart.html?highlight=piechart), we have sample code. 
`roslaunch jsk_rviz_plugins overlay_sample.launch` shows below by default.

![Screenshot from 2021-11-24 19-40-18](https://user-images.githubusercontent.com/42209144/143223390-66750e4d-dbe6-4f65-9c14-b771e32ae458.png)

You can manually select the color at foreground color. 

![Screenshot from 2021-11-24 19-39-40](https://user-images.githubusercontent.com/42209144/143224072-bc5c37f5-3076-4f50-9748-4cc7acdb4665.png)

**Comment by shmpwk** [comment]
How about enabling `auto color change`?

**Comment by OmerKonan** [comment]
I found it but I can not set threshold to change color. Also I have 3 different situation so `auto color change` enabling helps but not exactly solves my problem. Thank you

**Comment by shmpwk** [comment]
Like this ? https://github.com/jsk-ros-pkg/jsk_visualization/pull/840

**Comment by OmerKonan** [comment]
> 

Yes, That's perfect solution. Thank you so much!
