### ISSUE TITLE
How to offline install this package?

### ISSUE THREAD

**Issue by Charlie-lusie** [jsk-ros-pkg/jsk_visualization#858]
As title said, I want to use jsk visulization on a offline x86 ubuntu 20.04 machine. I tried to directly compile the source code, but error occurred. Can any one tell me how to offline install jsk vis?

**Comment by knorth55** [comment]
we can build this package without internet.
please paste the whole build output.
we want to know the error.

**Comment by Charlie-lusie** [comment]
> we can build this package without internet. please paste the whole build output. we want to know the error.

I put the package into a ros workspace folder like this:
ws_jsk/
         src/
                jsk_visualizatoion_msater/
                        jsk_inter.../
                        jsk_rqt/
                        jsk_rviz/
                        jsk_visualization/
                other_package/
the output is:
CMake Error at /opt/ros/noetic/share/catkin/cmake/catkinConfig.cmake: 83(find_package):
    Could not find a package configuration file provided by "jsk_hark_msgs"
     with any of the following names:
            jsk_hark_msgsConfig.cmake
            jsk_hark_msgs-config.cmake
Add the installation prefix of "jsk_hark_msgs" to CMAKE_PREFIX_PATH or set "jsk_hark_msgs_DIR" ...

**Comment by knorth55** [comment]
please install the dependencies
```
cd ws_jsk
rosdep install --from-path src -y -r -i
```

**Comment by knorth55** [comment]
you need jsk_common_msgs and pther dependencies.
i dont know how you download the source but you can download deb file from ros server and manually install it, or download source and build it
