### ISSUE TITLE
scale issue of Plotter2D

### ISSUE THREAD

**Issue by HMX2013** [jsk-ros-pkg/jsk_visualization#862]
Thanks for your great work, when using the the jsk rviz plugins in ubutnu or vmware, I found that if the scale value of the display  is not 100%, It may have the following problem. I don't see any option to change the font size of this value in Plotter2D. This problem puzzle me, hope it can be solve on day.
![屏幕截图 2022-11-26 170839](https://user-images.githubusercontent.com/105980724/204081927-c5b8d919-5f26-43a4-847a-d83dfb1f8b81.png)

**Comment by mqcmd196** [comment]
@HMX2013 Please try https://github.com/jsk-ros-pkg/jsk_visualization/pull/878
