### ISSUE TITLE
Are there any plans for compatibility with ros2 humble?

### ISSUE THREAD

**Issue by zz0320** [jsk-ros-pkg/jsk_visualization#881]
Now that ros2 has launched a long-term support version, is there any plan to update compatibility with humble.

**Comment by mqcmd196** [comment]
Hi @zz0320 
We want to do it, but we have limited resources, so if there are any contributors, we are always welcome. Please see https://github.com/jsk-ros-pkg/jsk_visualization/issues/779 
Anyone can fork this repo and create PR.
